---
name: Report

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

jobs:
  report:
    name: KSS Github Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Heimdall-rs
        uses: actions/checkout@v3
      
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Get Date
        id: date
        run: echo "TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Retreive cached dependecies
        uses: Swatinem/rust-cache@v2

      - name: Generate Report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd heimdall-rs
          cargo run --bin github-analytics 7 --print --csv
          mv kss-report-${{ env.TIME }}.csv ../

      - name: Archive Report
        uses: actions/upload-artifact@v3
        with:
          name: kss-reports
          path: kss-report-${{ env.TIME }}.csv
